[package]
name = "bip324"
version = "0.3.1"
edition = "2021"
license-file = "LICENSE"
description = "Encrypted messaging over the Bitcoin P2P Protocol as specified by BIP 324"
repository = "https://github.com/rust-bitcoin/bip324"
readme = "README.md"
rust-version = "1.63.0"

[features]
default = ["std"]
std = ["alloc", "bitcoin/std", "rand/std", "rand/std_rng"]
alloc = []

[dependencies]
rand = { version = "0.8.0", default-features = false }
bitcoin = { version = "0.32.0", default-features = false }

[dev-dependencies]
hex = { package = "hex-conservative", version = "0.2.0" }

[lib]
name = "bip324"
path = "src/lib.rs"

