[package]
name = "bip324-proxy"
version = "0.2.0"
edition = "2021"
license-file = "LICENSE"
description = "BIP324 proxy enabling v1-only clients to use the v2 Bitcoin P2P Protocol"
repository = "https://github.com/rust-bitcoin/bip324"
readme = "README.md"
rust-version = "1.63.0"

[package.metadata.configure_me]
spec = "config_spec.toml"

[dependencies]
bitcoin = { version = "0.32.0" }
tokio = { version = "1.37.0", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["compat"] }
hex = { package = "hex-conservative", version = "0.2.0" }
bip324 = { path = "../protocol", features = ["async"] }
configure_me = "0.4.0"

[build-dependencies]
configure_me_codegen = { version = "0.4.8", default-features = false }
